#! /usr/bin/env php
<?php

$autoloadPaths = [
    // Try to load autoloader if Concentrate is the root project.
    __DIR__ . '/../vendor/autoload.php',

    // Try to load an autoloader if Concentrate is installed as a library for
    // another root project.
    __DIR__ . '/../../../autoload.php',
];

foreach ($autoloadPaths as $path) {
    if (file_exists($path)) {
        require_once $path;
        break;
    }
}

$compiledCache = new Concentrate_FileCache(
    '/var/cache/concentrate/compiled-cache',
    __DIR__ . '/../compiled-cache'
);

$minifiedCache = new Concentrate_FileCache(
    '/var/cache/concentrate/minified-cache',
    __DIR__ . '/../minified-cache'
);

$cli = new Concentrate_CLI();
$cli->setCompiledCache($compiledCache);
$cli->setMinifiedCache($minifiedCache);
$cli->run();
