#! /usr/bin/env php
<?php

$autoload = __DIR__ . '/../vendor/autoload.php';
if (file_exists($autoload)) {
	require_once $autoload;
}

require_once 'Concentrate/CLI.php';

$cli = new Concentrate_CLI();
$cli->run();

?>
